### ISSUE TITLE
Implement APCA color ratio

### ISSUE THREAD

**Issue by RillingDev** [FelixRilling/colo.rs#3]
https://github.com/Myndex/apca-w3

**Comment by Myndex** [comment]
Hi @FelixRilling 

I just wanted to mention that the link you have listed there points to obsolete code. The correct code is now available as a package.

**APCA for the W3 is also available as an NPM package:**

     npm i apca-w3

And we recently released Bridge PCA which is backwards compatible with WCAG 2 contrast, but using APCA technology.

     npm i bridge-pca

Please let me know if you have any questions, our discussions tab is open at the repo.

https://github.com/Myndex/SAPC-APCA/discussions

Thank you

Andy

**Comment by RillingDev** [comment]
> Hi FelixRilling
> 
> I just wanted to mention that the link you have listed there points to obsolete code. The correct code is now available as a package.

Thank you! I will take a look at the resources you linked.
